[options]
girs_dir = "gir-files"
library = "Gdk"
version = "4.0.1"
min_cfg_version = "4.0.1"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Gdk.AnchorHints",
    "Gdk.AxisFlags",
    "Gdk.AxisUse",
    "Gdk.CairoContext",
    "Gdk.ContentFormatsBuilder",
    "Gdk.ContentProvider",
    "Gdk.CrossingMode",
    "Gdk.Device",
    "Gdk.DevicePad",
    "Gdk.DevicePadFeature",
    "Gdk.DeviceToolType",
    "Gdk.Drag",
    "Gdk.DragAction",
    "Gdk.DragCancelReason",
    "Gdk.DragSurface",
    "Gdk.EventSequence",
    "Gdk.EventType",
    "Gdk.FrameClock",
    "Gdk.FrameClockPhase",
    "Gdk.FrameTimings",
    "Gdk.FullscreenMode",
    "Gdk.GLContext",
    "Gdk.GLError",
    "Gdk.Gravity",
    "Gdk.InputSource",
    "Gdk.KeyMatch",
    "Gdk.MemoryFormat",
    "Gdk.MemoryTexture",
    "Gdk.ModifierType",
    "Gdk.NotifyType",
    "Gdk.Paintable",
    "Gdk.PaintableFlags",
    "Gdk.Popup",
    "Gdk.ScrollDirection",
    "Gdk.Seat",
    "Gdk.SeatCapabilities",
    "Gdk.Snapshot",
    "Gdk.SubpixelLayout",
    "Gdk.SurfaceEdge",
    "Gdk.Texture",
    "Gdk.ToplevelLayout",
    "Gdk.ToplevelState",
    "Gdk.TouchpadGesturePhase",
    "Gdk.VulkanContext",
    "Gdk.VulkanError",
]

manual = [
    "cairo.Content",
    "cairo.Context",
    "cairo.Region",
    "cairo.Surface",
    "Gdk.ButtonEvent",
    "Gdk.CrossingEvent",
    "Gdk.DeleteEvent",
    "Gdk.DNDEvent",
    "Gdk.Event", # Fundemental type, manual
    "Gdk.FocusEvent",
    "Gdk.GrabBrokenEvent",
    "Gdk.KeyEvent",
    "Gdk.KeymapKey",
    "Gdk.MotionEvent",
    "Gdk.PadEvent",
    "Gdk.ProximityEvent",
    "Gdk.Rectangle",
    "Gdk.RGBA",
    "Gdk.ScrollEvent",
    "Gdk.TimeCoord",
    "Gdk.TouchEvent",
    "Gdk.TouchpadEvent",
    "GdkPixbuf.Pixbuf",
    "Gio.AppLaunchContext",
    "Gio.Cancellable",
    "Gio.File",
    "Gio.Icon",
    "Gio.InputStream",
    "Gio.ListModel",
    "Gio.OutputStream",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Priority",
    "GLib.Quark",
    "GLib.String",
    "GObject.Value",
    "Pango.Direction",
    "Pango.Layout",
    "Pango.LayoutLine",
]

[[object]]
name = "Gdk.*"
status = "generate"
    [[object.function]]
    pattern = ".+"
        [[object.function.parameter]]
        name = "cr"
        const = true
        [[object.function.parameter]]
        name = "surface"
        const = true
    [[object.function]]
    pattern = "cairo_.+"
    #manual trait
    ignore = true
    [[object.function]]
    name = "pango_layout_get_clip_region"
    manual = true
    [[object.function]]
    name = "pango_layout_line_get_clip_region"
    manual = true
    [[object.function]]
    name = "content_register_deserializer"
    manual = true
    [[object.function]]
    name = "content_register_serializer"
    manual = true
    [[object.function]]
    name = "content_serialize_async"
    manual = true # init assert
    [[object.function]]
    name = "content_deserialize_async"
    manual = true
    [[object.function]]
    name = "events_get_angle"
    manual = true # event is a fundemental type
    [[object.function]]
    name = "events_get_center"
    manual = true # event is a fundemental type
    [[object.function]]
    name = "events_get_distance"
    manual = true # event is a fundemental type
    [[object.function]]
    name = "keyval_convert_case"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_from_name"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_is_lower"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_is_upper"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_name"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_to_lower"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_to_unicode"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_to_upper"
    manual = true # manually handled by keys::Key


[[object]]
name = "Gdk.AppLaunchContext"
status = "generate"
generate_builder = true

[[object]]
name = "Gdk.Clipboard"
status = "generate"
generate_builder = true
    [[object.function]]
    name = "read_async"
    manual = true # array

[[object]]
name = "Gdk.ContentDeserializer"
status = "generate"
    [[object.function]]
    name = "get_input_stream"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_mime_type"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_task_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_user_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_value"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "set_task_data"
    ignore = true # unsafe

[[object]]
name = "Gdk.ContentFormats"
status = "generate"
    [[object.function]]
    name = "get_gtypes"
    ignore = true # TODO: figure this out

[[object]]
name = "Gdk.ContentSerializer"
status = "generate"
    [[object.function]]
    name = "get_mime_type"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_output_stream"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_task_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_user_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_value"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "set_task_data"
    ignore = true #unsafe

[[object]]
name = "Gdk.Cursor"
status = "generate"
generate_builder = true

[[object]]
name = "Gdk.DeviceTool"
status = "generate"
generate_builder = true

[[object]]
name = "Gdk.Display"
status = "generate"
    [[object.function]]
    name = "get_app_launch_context"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_clipboard"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_default_group"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_default_seat"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_keymap"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_name"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_primary_clipboard"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_primary_monitor"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "translate_key"
    manual = true # to return a Key instead of a u32
    [[object.function]]
    name = "map_keycode"
    ignore = true # TODO: requires FromGlibPtrArrayContainerAsVec first
    [[object.function]]
    name = "map_keyval"
    ignore = true # TODO: requires FromGlibPtrArrayContainerAsVec first
    [[object.function]]
    name = "put_event"
    manual = true # event is a fundemental type

[[object]]
name = "Gdk.DisplayManager"
status = "generate"
generate_builder = true

[[object]]
name = "Gdk.DrawContext"
status = "generate"
manual_traits = ["DrawContextExtManual"]
    [[object.function]]
    name = "get_frame_region"
    manual = true

[[object]]
name = "Gdk.Drop"
status = "generate"
    [[object.function]]
    name = "read_async"
    manual = true # const ptr

[[object]]
name = "Gdk.GLTexture"
status = "generate"
    [[object.function]]
    name = "new"
    manual = true

[[object]]
name = "Gdk.Monitor"
status = "generate"
generate_builder = true

[[object]]
name = "Gdk.PopupLayout"
status = "generate"
manual_traits = ["PopupLayoutExtManual"]
    [[object.function]]
    name = "get_offset"
    manual = true # invalid mutability

[[object]]
name = "Gdk.Surface"
status = "generate"
manual_traits = ["SurfaceExtManual"]
    [[object.function]]
    name = "create_similar_surface"
    manual = true
    [[object.function]]
    name = "set_opaque_region"
        [[object.function.parameter]]
        name = "region"
        const = true
    [[object.function]]
    name = "translate_coordinates"
    manual = true # mutability issue

[[object]]
name = "Gdk.Toplevel"
status = "generate"
manual_traits = ["ToplevelExtManual"]
    [[object.function]]
    name = "inhibit_system_shortcuts"
    manual = true # event is a fundemental type
    [[object.function]]
    name = "show_window_menu"
    manual = true # event is a fundemental type
