[options]
girs_dir = "gir-files"
library = "Gsk"
version = "4.0"
min_cfg_version = "4.0.1"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Gsk.BlendMode",
    "Gsk.BlendNode",
    "Gsk.BlurNode",
    "Gsk.CairoNode",
    "Gsk.CairoRenderer",
    "Gsk.ClipNode",
    "Gsk.ColorMatrixNode",
    "Gsk.ColorNode",
    "Gsk.ContainerNode",
    "Gsk.Corner",
    "Gsk.CrossFadeNode",
    "Gsk.DebugNode",
    "Gsk.GLRenderer",
    "Gsk.GLShaderNode",
    "Gsk.GLUniformType",
    "Gsk.InsetShadowNode",
    "Gsk.OpacityNode",
    "Gsk.OutsetShadowNode",
    "Gsk.Renderer",
    "Gsk.RenderNodeType",
    "Gsk.RepeatNode",
    "Gsk.RoundedClipNode",
    "Gsk.ScalingFilter",
    "Gsk.SerializationError",
    "Gsk.ShaderArgsBuilder",
    "Gsk.TextNode",
    "Gsk.TextureNode",
    "Gsk.TransformCategory",
    "Gsk.TransformNode",
]

manual = [
    "cairo.Context",
    "cairo.Region",
    "cairo.Surface",
    "Gdk.RGBA",
    "Gdk.Surface",
    "Gdk.Texture",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Quark",
    "GLib.String",
    "Graphene.Matrix",
    "Graphene.Point",
    "Graphene.Point3D",
    "Graphene.Rect",
    "Graphene.Size",
    "Graphene.Vec2",
    "Graphene.Vec3",
    "Graphene.Vec4",
    "Gsk.ColorStop",
    "Gsk.RoundedRect",
    "Gsk.Shadow",
    "Pango.Font",
    "Pango.GlyphInfo",
    "Pango.GlyphString",
]

[[object]]
name = "Gsk.*"
status = "generate"

[[object]]
name = "Gsk.BorderNode"
status = "generate"
manual_traits = ["BorderNodeManualExt"]
    [[object.function]]
    name = "get_widths"
    # gir fails to generate a fixed-size=4 array
    manual = true

[[object]]
name = "Gsk.BroadwayRenderer"
status = "generate"
cfg_condition = "feature = \"broadway\""

[[object]]
name = "Gsk.ConicGradientNode"
status = "generate"
    [[object.function]]
    name = "new"
    # uses &[&ColorStop] instead of a &[ColorStop]
    manual = true


[[object]]
name = "Gsk.GLShader"
status = "generate"
generate_builder = true

[[object]]
name = "Gsk.LinearGradientNode"
status = "generate"
    [[object.function]]
    name = "new"
    # uses &[&ColorStop] instead of a &[ColorStop]
    manual = true

[[object]]
name = "Gsk.RadialGradientNode"
status = "generate"
    [[object.function]]
    name = "new"
    # uses &[&ColorStop] instead of a &[ColorStop]
    manual = true

[[object]]
name = "Gsk.RenderNode"
status = "generate"
    [[object.function]]
    name = "draw"
        [[object.function.parameter]]
            name = "cr"
            const = true

[[object]]
name = "Gsk.RepeatingLinearGradientNode"
status = "generate"
    [[object.function]]
    name = "new"
    # uses &[&ColorStop] instead of a &[ColorStop]
    manual = true

[[object]]
name = "Gsk.RepeatingRadialGradientNode"
status = "generate"
    [[object.function]]
    name = "new"
    # uses &[&ColorStop] instead of a &[ColorStop]
    manual = true


[[object]]
name = "Gsk.ShadowNode"
status = "generate"
    [[object.function]]
    name = "new"
    # uses &[&Shadow] instead of a &[Shadow]
    manual = true
    [[object.function]]
    name = "get_shadow"
    # needs an assertion that the i < n_shadows
    manual = true

[[object]]
name = "Gsk.Transform"
status = "generate"
    [[object.function]]
    name = "equal"
        [[object.function.parameter]]
            name = "second"
            nullable = false

[[object]]
name = "Gsk.VulkanRenderer"
status = "generate"
cfg_condition = "feature = \"vulkan\""
